# This is a basic workflow to help you get started with Actions

name: CI & CD Backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push for any branch and only if the frontend has changed
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Setup JVM'
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: 'Build'
        uses: gradle/gradle-build-action@v1

        env:
          DOCKERHUB_USER: st4udi
          DOCKERHUB_PWD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        with:
          gradle-executable: ./gradle
          arguments:

            test
            jib --image=st4udi/zackathon-game

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        # if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: 'zackathon-grid-game'
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: st4udi/zackathon-game
          name: game-backend
          location: 'west eu'
