# This is a basic workflow to help you get started with Actions

name: CI & CD Backend

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup JVM'
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - run: chmod +x ./gradlew

      - name: 'Build'
        uses: gradle/gradle-build-action@v1
        env:
          DOCKERHUB_USER: st4udi
          DOCKERHUB_PWD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        with:
          arguments:
            :backend:test
            jib --image=st4udi/zackathon-game

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: 'zackathon-grid-game'
          dns-name-label: zackathon-game
          memory: 0.5
          ports: 8080:80
          image: st4udi/zackathon-game
          name: game-backend
          location: 'westeurope'
